project 'EAACosmosBank.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'EAACosmosBank' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking'
  pod 'Realm'

end
